config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root to: 'events#index'
  resources :events, only: %i[index show]
  resources :about, only: :index
  resources :contacts, only: :index
  resources :email_subscriptions, only: %i[create show destroy], param: :uuid

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_subscription.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: email_subscriptions
#
#  id         :bigint           not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  uuid       :uuid
#

class EmailSubscription < ApplicationRecord
  validates :email, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id            :bigint           not null, primary key
#  title         :string
#  date          :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  youtube_link  :string
#  mixcloud_link :string
#  publish       :boolean
#

class Event < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  has_many :event_speakers
  has_many :speakers, through: :event_speakers

  validates :title, presence: true
  validates :date, presence: true
  validates :description, presence: true

  default_scope { order(date: :desc) }

  def self.published
    where(publish: true)
  end
end

app/models/event_speaker.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: event_speakers
#
#  id         :bigint           not null, primary key
#  event_id   :bigint
#  speaker_id :bigint
#

class EventSpeaker < ApplicationRecord
  belongs_to :event
  belongs_to :speaker
end

app/models/fact.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: facts
#
#  id          :bigint           not null, primary key
#  number      :bigint
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  publish     :boolean          default(FALSE)
#

class Fact < ApplicationRecord
  validates :number, presence: true
  validates :title, presence: true
end

app/models/member.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: members
#
#  id          :bigint           not null, primary key
#  first_name  :string
#  last_name   :string
#  position    :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  publish     :boolean          default(FALSE)
#

class Member < ApplicationRecord
  has_one_attached :image

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/speaker.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: speakers
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Speaker < ApplicationRecord
  has_many :event_speakers
  has_many :events, through: :event_speakers

  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index
    members = Member.all
    facts = Fact.all
    render :index, locals: { members: members, facts: facts }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/avo/email_subscriptions_controller.rb
# frozen_string_literal: true

# This controller has been generated to enable Rails' resource routes.
# You shouldn't need to modify it in order to use Avo.
class Avo::EmailSubscriptionsController < Avo::ResourcesController
end

app/controllers/avo/events_controller.rb
# frozen_string_literal: true

# This controller has been generated to enable Rails' resource routes.
# You shouldn't need to modify it in order to use Avo.
class Avo::EventsController < Avo::ResourcesController
end

app/controllers/avo/speakers_controller.rb
# frozen_string_literal: true

# This controller has been generated to enable Rails' resource routes.
# You shouldn't need to modify it in order to use Avo.
class Avo::SpeakersController < Avo::ResourcesController
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def index; end
end

app/controllers/email_subscriptions_controller.rb
# frozen_string_literal: true

class EmailSubscriptionsController < ApplicationController
  around_action :switch_locale

  def show
    email_to_destroy = EmailSubscription.find_by(uuid: params[:uuid])

    render 'show', locals: { email_to_destroy: email_to_destroy }, layout: 'service'
  end

  def create
    new_sub = EmailSubscription.new(sub_params)

    return if valid_subscrition?(new_sub)
    return if invalid_subscription?(new_sub)

    respond_to { |format| format.json { head :error } }
  end

  def destroy
    email_to_destroy = find_email

    if email_to_destroy.destroy!
      redirect_to root_path
    else
      respond_to do |format|
        format.json { head :error }
      end
    end
  end

  private

  def sub_params
    params.require(:email_subscription).permit(:email)
  end

  def find_email
    EmailSubscription.find_by(uuid: params[:uuid])
  end

  def switch_locale(&action)
    # locale = params[:locale] || I18n.default_locale
    I18n.with_locale(:uk, &action)
  end

  def valid_subscrition?(new_sub)
    return unless new_sub.valid?

    capcha = verify_recaptcha(action: 'submit_email')
    return unless capcha

    new_sub.save!
    respond_to do |format|
      format.json { head :ok }
      UserMailer.welcome_for_subscriber(new_sub).deliver_later
    end
  end

  def invalid_subscription?(new_sub)
    errors = new_sub.errors.details[:email]
    return unless errors.select { |el| el[:error] == :taken }

    respond_to do |format|
      format.json { head :conflict } # e.g. 409
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events ||= Events::IndexPageRepository.new(Event).paginate(params[:page])

    respond_to do |format|
      format.html
      format.json do
        render json: {
          entries: render_to_string(partial: 'events', formats: [:html]),
          pagination: view_context.paginate(@events)
        }
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def display_events_on_main; end
end

app/views/about/index.html.slim
main.main
  = render 'layouts/partials/banner'
  div.container.cf-philo-list.about-what-we-do
    div.row.d-none.d-lg-block
    div.row
      div.col-12.cf-philo-title
        h2 Що ми робимо
    div.row.cf-philo-row.align-items-center
      div.col-12.col-lg-6.cf-philo-row__image-wrapper.d-none.d-lg-block
        p.cf-philo-row__circle
      div.col-12.col-lg-6
        div.cf-philo-row__info
          p Café Philosophique — це відкритий майданчик, де відбувається філософський діалог, обмін ідеями та інтелектуальним досвідом у публічному просторі міста. Ми маємо справу лише з фахівцями, що мають знакові наукові здобутки у своїй галузі й відкриті до діалогу.

          p Cafe-philo - це культурне явище, яке виникло у 20му столітті у Франції, його засновником вважається Марк Соте (Marc Sautet). Згодом це явище поширилось на інші міста Франції та Європи загалом.
          p Основна мета подій Сafé philosophique у Львові, це популяризація філософії в Україні.
  - if members.size > 0
    div.container.cf-philo-list
      div.row.d-none.d-lg-block
      div.row
        div.col-12.cf-philo-title
          h2 Наша команда
      - members.each do |member|
        div.row.cf-philo-row.align-items-center
          div.col-12.col-lg-6.cf-philo-row__image-wrapper
            - if member.image.attached?
              div.cf-philo-row__image.d-flex.align-items-center
                = image_tag member.image
            p.cf-philo-row__circle
          div.col-12.col-lg-6
            div.cf-philo-row__info
              h3
                = "#{member.first_name} #{member.last_name}"
              h4
                = member.position
              div.
                = member.description
  - if facts.size > 0
    div.container.cf-philo-list
      div.row.d-none.d-lg-block
      div.row
        div.col-12.cf-philo-title
          h2 Факти про нас
      - facts.each do |fact|
        div.row.cf-philo-row.align-items-center
          div.col-12.col-lg-6.cf-philo-row__image-wrapper
            div.cf-philo-row__fact-number
              div.cf-philo-title
                h2
                  = fact.number
            p.cf-philo-row__circle
          div.col-12.col-lg-6
            div.cf-philo-row__info
              h3
                = fact.title
              div
                = fact.description

app/views/active_storage/blobs/_blob.html.slim
figure class=("attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}") 
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      span.attachment__name= blob.filename
      span.attachment__size= number_to_human_size blob.byte_size

app/views/contacts/index.html.slim
main.main
  div.container
    div.row.banner
      div.banner__title.col-12.col-md-10.col-lg-8.offset-lg-2.d-flex.flex-column.justify-content-center
        h1 cafe philosophique lviv
        h2 простір свободи
    div.row.contacts
      div.col-12.col-md-10.col-lg-8.offset-lg-2.d-flex.flex-column.justify-content-center
        div.contacts__content.container
          div.row.align-items-center
            div.col-12.col-md-6
              | Café Philosophique — це відкритий майданчик, де відбувається філософський діалог, обмін ідеями та інтелектуальним досвідом у публічному просторі міста. Ми маємо справу лише з фахівцями, що мають знакові наукові здобутки у своїй галузі й відкриті до діалогу.
            div.col-12.col-md-6
              ul
                li
                  a href="tel:+380638727198"
                    span
                        i.fa.fa-phone
                    | (063) 872 71 98
                li
                  a href="mailto:cafephilo@gmail.com"
                    span
                      i.fa.fa-envelope-o
                    | cafephilo@gmail.com
      aside.banner__aside.col-12.col-md-2
        nav.socials
          ul.d-flex.flex-md-column
            li
              a href="https://www.youtube.com/channel/UC4f4aHcZLG68nnpDcthSKJA" target="blank"
                = image_tag "youtube.png"
            li
              a href="https://www.facebook.com/lvivcafephilo/" target="blank"
                = image_tag "facebook.png"
            li
              a href="https://t.me/cafephilolviv" target="blank"
                = image_tag "telegram.png"
            li
              a href="https://www.mixcloud.com/cafephilolviv" target="blank"
                = image_tag "mixcloud.png"

app/views/email_subscriptions/show.html.slim
main.main
  .container
    == button_to t("email.subscription.cancel"), email_subscription_url(email_to_destroy.uuid), method: :delete
    == button_to t("email.subscription.back"), root_url, method: :get

app/views/events/_events.html.slim
- event_year = 0
- @events.each do |event|
  div.row.cf-philo-row.event-row
    - if event_year == 0 || event_year != event.date.strftime("%Y")
      - event_year = event.date.strftime("%Y")
      div.col-12.event-year.cf-philo-title
        h2
          = event.date.strftime("%Y")
    div.col-12.col-lg-6.cf-philo-row__image-wrapper
      - if event.image.attached?
        div.cf-philo-row__image.event-row__image.d-flex.align-items-center
          = image_tag event.image
      p.cf-philo-row__circle.event-row__circle.event-date.d-flex.flex-column.justify-content-center.align-items-center
        span.event-date__day
          = event.date.strftime("%d") 
        span.event-date__month
          = event.date.strftime("%b")
    div.col-12.col-lg-6
      div.cf-philo-row__info.event-row__info.event-card{ data-id = event.id }
        h3
          = event.title
        h4
          = event.date.strftime("%d.%m.%Y")
        - unless event.speakers.size.zero?
          div.cf-philo-row__speakers
            h4.cf-philo-row__speakers-title
              - if event.speakers.size == 1
                | Спікер:
              - else
                | Спікери:
            ul.cf-philo-row__speakers-list
              - event.speakers.each do |speaker|
                li
                  h4
                    = "#{speaker.first_name} #{speaker.last_name}"
        div.event-row__desc.event-desc.with-height{ data-card-id = event.id }
          div.event-row__desc-inner.event-desc-inner
            = event.description.body.html_safe
        div.event-row__links.d-flex.justify-content-between.event-links{ data-card-id = event.id }
          button.event-row__read-more.read-more.button-with-arrow
            p.arrow
              span.arrow__line.arrow__line_left
              span.arrow__line.arrow__line_right
            | читати більше
          - if !event.youtube_link.nil? || !event.mixcloud_link.nil?
            ul.d-flex.socials
              - unless event.youtube_link.nil? || event.youtube_link.empty?
                li
                  a href="#{event.youtube_link}" target="blank"
                    = image_tag "youtube.png"
              - unless event.mixcloud_link.nil? || event.mixcloud_link.empty?
                li
                  a href="#{event.mixcloud_link}" target="blank"
                    = image_tag "mixcloud.png"

app/views/events/index.html.slim
main.main
  = render 'layouts/partials/banner'
  div data-controller='infinite-scroll' data-action='scroll@window->infinite-scroll#scroll'
    div.container.cf-philo-list.events-list
      - if @events.size > 0
          div data-infinite-scroll-target='entries'
            = render 'events'
    div.cf-philo-paginator.d-none
      div.container data-infinite-scroll-target='pagination'
        = paginate @events

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Admin dashboard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'admin/index', 'data-turbolinks-track': 'reload'
  body
    .admin__layout
      .admin__main
        .info
          = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/partials/meta'
    link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'
    link href='/favicon-32x32.png' rel='icon' sizes='32x32' type='image/png'
    link href='/favicon-16x16.png' rel='icon' sizes='16x16' type='image/png'
    link href='/site.webmanifest' rel='manifest'
    link color='#5bbad5' href='/safari-pinned-tab.svg' rel='mask-icon'
    meta content='#2d89ef' name='msapplication-TileColor'
    meta content='#ffffff' name='theme-color'
    title
      | Cafephilo Lviv | Cafe philosophique Lviv | Філософія Львів
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,700,700i&display=swap&subset=cyrillic-ext'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/partials/gtag'
  body
    = render 'layouts/partials/header'
    = yield
    = render 'layouts/partials/footer'

app/views/layouts/partials/_banner.html.slim
div.container
  div.row.banner
    div.banner__title.col-12.col-md-10.col-lg-8.offset-lg-2.d-flex.flex-column.justify-content-center
      h1 cafe philosophique lviv
      h2 простір свободи
    aside.banner__aside.col-12.col-md-2
      nav.socials
        ul.d-flex.flex-md-column
          li
            a href="https://www.youtube.com/channel/UC4f4aHcZLG68nnpDcthSKJA" target="blank"
              = image_tag "youtube.png"
          li
            a href="https://www.facebook.com/lvivcafephilo/" target="blank"
              = image_tag "facebook.png"
          li
            a href="https://t.me/cafephilolviv" target="blank"
              = image_tag "telegram.png"
          li
            a href="https://www.mixcloud.com/cafephilolviv" target="blank"
              = image_tag "mixcloud.png"

app/views/layouts/partials/_footer.html.slim
== javascript_pack_tag 'email_subscriptions'
footer.footer
  div.wrapper.wrapper-container
    div.footer__inner.d-flex.justify-content-lg-end.align-items-center
      button.to_top.button-with-arrow.active
        p.arrow
          span.arrow__line.arrow__line_left
          span.arrow__line.arrow__line_right
      div.footer__form.d-flex
        span.form-title Дізнавайтеся про події першими!
        == form_with(scope: :email_subscription,
                     url: email_subscriptions_path,
                     method: "post", remote: true) do |f|
          = f.text_field :email, placeholder: "Ваш e-mail"
          = recaptcha_v3 action: "submit_email"
          = f.submit "Підписатися", class: "button submit", id: 'submit__email'

app/views/layouts/partials/_google_analytics.html.slim
- if Rails.env.production?
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-87948087-1', 'auto');
      ga('send', 'pageview');

app/views/layouts/partials/_gtag.html.erb
<% if Rails.env.production? %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async   src="https://www.googletagmanager.com/gtag/js?id=<%=ENV['GOOGLE_ANALYTICS_ID'] %>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', "#{<%= ENV['GOOGLE_ANALYTICS_ID'] %>}");
    </script>
<% end %>

app/views/layouts/partials/_header.html.slim
header.header
  div.wrapper.wrapper-container
    div.header__inner.d-flex.justify-content-between.align-items-center
      div.header__logo
        a href="/"
          img
            = image_tag "logo.svg"
      nav.header__menu
        ul.d-flex
          li
            a href="/about" Про нас
          li
            a href="/contacts" Контакти

app/views/layouts/partials/_meta.html.erb
<meta content=("text/html; charset=UTF-8") http-equiv="Content-Type">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta
  name="google-site-verification"
  content="VSXojJ4i1Fqdzs5KTZzt1OZl-D92m6ifufh8I-CECqA"
>

<meta
  content="text/html; charset=UTF-8"
  http-equiv="Content-Type"
>

<meta
  name="keywords"
  content="Cafe Philo Lviv, Lviv Cafe philo, cafephilo,cafephilolviv, Кафе філо Львів, кафе філо львів, кафе філософік львів, cafe philosophique lviv, філософська кав'ярня, філософія львів, львів філософія, ЛНУ філософія, філософський львів"
>

<meta
  name="description"
  content="Філософська Кав'ярня Львів | Cafe Philosophique Lviv Official Site | Cafephilo Lviv | Кафе Філо Львів"
>

<meta property="og:title"
      content="Філософська Кав'ярня Львів | Cafe Philosophique Lviv Official Site | Cafephilo Lviv | Кафе Філо Львів"
>

<meta property="og:image" content=<%= image_url('preview_logo_cafe.png')%> >

app/views/layouts/service.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Admin dashboard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield